### ISSUE TITLE
Investigate XPASS tests

### ISSUE THREAD

**Issue by ajjackson** [RastislavTuranyi/resolution_functions#3]
We have some tests marked as XFAIL which nonetheless pass; this is related to the Lagrange low-frequency resolution discrepancy with Abins. Perhaps these tests have zero intensity down there?

**Comment by RastislavTuranyi** [comment]
Took a look, and it's the `Cu(331)`, `Si(311)`, and `Si(111)` options for the monochromator that are XPASS; all of those are expected to pass since in [AbINS they don't have a low-energy cut-off value](https://github.com/mantidproject/mantid/blob/cd5c613224d67803a34c999a94e731967e5c2767/scripts/abins/parameters.py#L113); only the `Cu(220)` monochromator has a defined cut-off:

```
        settings: &lagrange_settings
            monochromator:
                default_setting: "Cu(220)"
                Cu(220):
                    #ei_range: [26, 500]  # meV
                    fit: [-3.5961e-2, 2.156e-2, 7.6987e-5, ]  # meV
                    low_energy_cutoff: 25  # meV
                    low_energy_resolution: 0.8  # meV
                Cu(331):
                    #ei_range: [67, 500]  # meV
                    fit: [6.58362118e-01, 5.15925386e-04, 1.11911095e-04, -8.60511597e-08]  # meV
                Si(311):
                    #ei_range: [16.5, 60]  # meV
                    fit: [0.8]  # meV
                Si(111):
                    #ei_range: [4.5, 20]  # meV
                    fit: [0.8]  # meV
```
